In [2]:
import numpy as np
from numpy import linalg as LA

In [3]:
# dot product
a = np.array([1, 2, 3], dtype=int)
print("a = ")
print(a)
b = np.array([4, 5, 6], dtype=int)
print("b = ")
print(b)
print("a . b = ")
print(np.dot(a, b))

a = 
[1 2 3]
b = 
[4 5 6]
a . b = 
32


In [4]:
# norm
a = np.array([1, 2], dtype=int)
print("a = ")
print(a, "\n")

Euclidean_norm = LA.norm(a)  # default norm is Euclidean norm
print("Euclidean_norm = ")
print(Euclidean_norm, "\n")

maximum_norm = LA.norm(a, ord=np.inf)  # maximum norm
print("maximum_norm = ")
print(maximum_norm)
print()

Manhattan_norm = LA.norm(a, ord=1)   # 1-norm
print("Manhattan_norm = ")
print(Manhattan_norm)

a = 
[1 2] 

Euclidean_norm = 
2.23606797749979 

maximum_norm = 
2.0

Manhattan_norm = 
3.0


In [5]:
# matrix multiplication
a = np.array([[1, 2, 3], [8, 2, 1]], dtype=int)
print("a = ")
print(a)
print()

b = np.array([[2, 5, 7], [1, 5, 8], [3, 1, 2]], dtype=int)
print("b = ")
print(b)
print()

print("a * b = ")
print(np.matmul(a, b))

a = 
[[1 2 3]
 [8 2 1]]

b = 
[[2 5 7]
 [1 5 8]
 [3 1 2]]

a * b = 
[[13 18 29]
 [21 51 74]]


In [6]:
# eigenvalues and eigenvectors
a = np.array([[2, 1], [1, 2]])
print("a = ")
print(a)
lam, p = LA.eig(a)
print("eigenvalues = ")
print(lam)
print("eigenvectors = ")
print(p)
print()

b = np.array([[3, 6, -8], [0, 0, 6], [0, 0, 2]])
print("b = ")
print(b)
lam, p = LA.eig(b)
print("eigenvalues = ")
print(lam)
print("eigenvectors = ")
print(p)

a = 
[[2 1]
 [1 2]]
eigenvalues = 
[3. 1.]
eigenvectors = 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

b = 
[[ 3  6 -8]
 [ 0  0  6]
 [ 0  0  2]]
eigenvalues = 
[3. 0. 2.]
eigenvectors = 
[[ 1.         -0.89442719 -0.95346259]
 [ 0.          0.4472136   0.28603878]
 [ 0.          0.          0.09534626]]


In [7]:
# algebraic and geometric multiplicities
c = np.array([[1, 1], [0, 1]], dtype=int)
print("c = ")
print(c)
lam, p = LA.eig(c)
print("eigenvalues = ")
print(lam)
print("eigenvectors = ")
print(p)
print()

d = np.array([[1, 0], [0, 1]], dtype=int)
print("d = ")
print(d)
lam, p = LA.eig(d)
print("eigenvalues = ")
print(lam)
print("eigenvectors = ")
print(p)
print()

c = 
[[1 1]
 [0 1]]
eigenvalues = 
[1. 1.]
eigenvectors = 
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]

d = 
[[1 0]
 [0 1]]
eigenvalues = 
[1. 1.]
eigenvectors = 
[[1. 0.]
 [0. 1.]]



In [10]:
# eigendecomposition of a matrix
a = np.array([[1, 0], [1, 3]])
lam, p = LA.eig(a)
print("a = ")
print(a)

diagonal_matrix = np.diag(lam)
print("diagonal_matrix = ")
print(diagonal_matrix)
print("eigendecomposition of a = ")
print(np.matmul(np.matmul(p, diagonal_matrix), LA.inv(p)))
print()

b = np.array([[1, 2, 0], [0, 3, 0], [2, -4, 2]])
print("b = ")
print(b)
lam, p = LA.eig(b)
print("lam = ")
print(lam)
print("eigendecomposition of b = ")
print(np.matmul(np.matmul(p, np.diag(lam)), LA.inv(p)))


arr = np.array([[-2,0],[1,1]])
print(LA.inverse(arr))

a = 
[[1 0]
 [1 3]]
diagonal_matrix = 
[[3. 0.]
 [0. 1.]]
eigendecomposition of a = 
[[1. 0.]
 [1. 3.]]

b = 
[[ 1  2  0]
 [ 0  3  0]
 [ 2 -4  2]]
lam = 
[2. 1. 3.]
eigendecomposition of b = 
[[ 1.  2.  0.]
 [ 0.  3.  0.]
 [ 2. -4.  2.]]


AttributeError: module 'numpy.linalg' has no attribute 'inverse'